---
version: "3.7"

services:
  traefik:
    networks:
      ocis-net:
        aliases:
          - ${OCIS_DOMAIN:-ocis.owncloud.test}
    depends_on:
      - web
    extends:
        file: docker-compose.base.yml
        service: traefik

  ocis:
    networks:
      ocis-net:
      ocis-int:
        aliases:
          - idp.owncloud.test
          - storage-frontend.owncloud.test
          - storage-gateway.owncloud.test
          - ocs.owncloud.test
          - accounts.owncloud.test
          - settings.owncloud.test
          - webdav.owncloud.test
    extends:
        file: docker-compose.base.yml
        service: ocis
    environment:
      OCIS_RUN_EXTENSIONS: accounts, glauth, idp, ocs, proxy, settings, storage-appprovider, storage-authbasic, storage-authbearer, storage-auth-machine, storage-frontend, storage-gateway, storage-groupprovider, storage-metadata, storage-public-link, storage-shares, storage-sharing, storage-userprovider, storage-users, store, thumbnails, webdav
      # settings,storage-metadata,graph,graph-explorer,ocs,store,thumbnails,web,webdav,storage-frontend,storage-gateway,storage-userprovider,storage-groupprovider,storage-authbasic,storage-authbearer,storage-authmachine,storage-users,storage-shares,storage-public-link,storage-appprovider,storage-sharing,proxy
      OCIS_COMMAND: server
      IDP_HTTP_ADDR: 0.0.0.0:9130
      OCS_HTTP_ADDR: 0.0.0.0:9110
      STORAGE_FRONTEND_HTTP_ADDR: 0.0.0.0:9140
      SETTINGS_HTTP_ADDR: 0.0.0.0:9190
      ACCOUNTS_HTTP_ADDR: 0.0.0.0:9181
      WEBDAV_HTTP_ADDR: 0.0.0.0:9115
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.entrypoints=https"
      # maps based on domain from https --> ocis.owncloud.test:9200
      - "traefik.http.routers.proxy.rule=Host(`${OCIS_DOMAIN:-ocis.owncloud.test}`)"
      - "traefik.http.routers.proxy.tls.certresolver=http"
      - "traefik.http.routers.proxy.service=proxy"
      - "traefik.http.services.proxy.loadbalancer.server.port=9200"
      # IMPORTANT - otherwise it will bind to "ocis-int" (although it should not be able to)
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_ocis-net"

  web:
    depends_on:
      - ocis
    extends:
        file: docker-compose.base.yml
        service: ocis
    networks:
      ocis-int:
        aliases:
          - web.owncloud.test
    environment:
      OCIS_RUN_EXTENSIONS: web
      OCIS_COMMAND: server

      WEB_HTTP_ADDR: web.owncloud.test:9100
      # override config.json
      WEB_UI_CONFIG: /etc/ocis/config.json
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    ports:
      - 9100:9100

  # webdav:
  #   depends_on:
  #     - ocis
  #   extends:
  #       file: docker-compose.base.yml
  #       service: ocis
  #   networks:
  #     ocis-int:
  #       aliases:
  #         - webdav.owncloud.test
  #   environment:
  #     OCIS_RUN_EXTENSIONS: webdav
  #     OCIS_COMMAND: server

  #     WEBDAV_HTTP_ADDR: webdav.owncloud.test:9115
  #   entrypoint:
  #     - /bin/sh
  #     - /entrypoint-override.sh
  #   ports:
  #     - 9115:9115

  graph:
    depends_on:
      - ocis
    extends:
        file: docker-compose.base.yml
        service: ocis
    networks:
      ocis-int:
        aliases:
          - graph.owncloud.test
    environment:
      OCIS_RUN_EXTENSIONS: graph
      OCIS_COMMAND: server

      GRAPH_HTTP_ADDR: graph.owncloud.test:9120
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    ports:
      - 9120:9120

  graph-explorer:
    depends_on:
      - ocis
    extends:
        file: docker-compose.base.yml
        service: ocis
    networks:
      ocis-int:
        aliases:
          - graph-explorer.owncloud.test
    environment:
      OCIS_RUN_EXTENSIONS: graph-explorer
      OCIS_COMMAND: server

      GRAPH_EXPLORER_HTTP_ADDR: graph-explorer.owncloud.test:9135
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    ports:
      - 9135:9135

volumes:
  certs:
  ocis-data:

networks:
  ocis-net:
    ipam:
      config:
        - subnet: 172.177.0.0/16
  ocis-int:
    ipam:
      config:
        - subnet: 10.103.0.1/16
