---
version: "3.7"


# https://github.com/owncloud/ocis/blob/master/docs/extensions/storage/ports.md

services:
  traefik:
    networks:
      ocis-net:
        aliases:
          - ${OCIS_DOMAIN:-ocis.owncloud.test}
    depends_on:
      - web
    extends:
        file: docker-compose.base.yml
        service: traefik

  ocis:
    networks:
      ocis-net:
      ocis-int:
        aliases:
          - idp.owncloud.test
          - storage-frontend.owncloud.test
          - storage-gateway.owncloud.test
          - ocs.owncloud.test
          - accounts.owncloud.test
          - settings.owncloud.test
          - webdav.owncloud.test
    extends:
        file: docker-compose.base.yml
        service: ocis
    environment:
    # doesn't work if OCS is first
      OCIS_RUN_EXTENSIONS: accounts, glauth, idp, settings, ocs, storage-appprovider, storage-authbasic, storage-authbearer, storage-auth-machine, storage-frontend, storage-gateway, storage-groupprovider, storage-metadata, storage-public-link, storage-shares, storage-sharing, storage-userprovider, storage-users, store, thumbnails, webdav
      # settings,storage-metadata,graph,graph-explorer,ocs,store,thumbnails,web,webdav,storage-frontend,storage-gateway,storage-userprovider,storage-groupprovider,storage-authbasic,storage-authbearer,storage-authmachine,storage-users,storage-shares,storage-public-link,storage-appprovider,storage-sharing,proxy
      OCIS_COMMAND: server
      IDP_HTTP_ADDR: 0.0.0.0:9130
      OCS_HTTP_ADDR: 0.0.0.0:9110
      WEBDAV_HTTP_ADDR: 0.0.0.0:9115
      ACCOUNTS_HTTP_ADDR: 0.0.0.0:9181
      ACCOUNTS_GRPC_ADDR: 0.0.0.0:9180
      STORAGE_FRONTEND_HTTP_ADDR: 0.0.0.0:9140
      STORAGE_GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      REVA_GATEWAY: storage-gateway.owncloud.test:9142
      SETTINGS_HTTP_ADDR: 0.0.0.0:9190
      SETTINGS_GRPC_ADDR: 0.0.0.0:9191 # ocs depends on this
      WEBDAV_LOG_LEVEL: debug

      # it's referencing storage 127.0.0.1 for something.... ?

      STORAGE_METADATA_GRPC_ADDR: 0.0.0.0:9215 # for accounts
      STORAGE_METADATA_HTTP_ADDR: 0.0.0.0:9216 # ERROR
      # STORAGE_METADATA_GRPC_PROVIDER_ADDR: 0.0.0.0:9215 accounts?
      # STORAGE_METADATA_PORT_HTTP_ADDR: 0.0.0.0:9216
      # STORAGE_METADATA_PORT_GRPC_ADDR: 0.0.0.0:9215
      STORAGE_METADATA_DRIVER: ocis # default
      # STORAGE_METADATA_ROOT: '/tmp'
      # ACCOUNTS_STORAGE_BACKEND: cs3
      # ACCOUNTS_STORAGE_CS3_PROVIDER_ADDR: storage-metadata.owncloud.test:9215

    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.proxy.entrypoints=https"
    #   # maps based on domain from https --> ocis.owncloud.test:9200
    #   - "traefik.http.routers.proxy.rule=Host(`${OCIS_DOMAIN:-ocis.owncloud.test}`)"
    #   - "traefik.http.routers.proxy.tls.certresolver=http"
    #   - "traefik.http.routers.proxy.service=proxy"
    #   - "traefik.http.services.proxy.loadbalancer.server.port=9200"
    #   # IMPORTANT - otherwise it will bind to "ocis-int"
    #   - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_ocis-net"
    ports:
      - 9140:9140 # for remote.php (storage frontend)
      - 9142:9142 # reva, for ocs

  proxy:
    extends:
        file: docker-compose.base.yml
        service: ocis
    networks:
      ocis-int:
      ocis-net:
    # depends_on:
    #   - ocis
    environment:
      OCIS_RUN_EXTENSIONS: proxy
      OCIS_COMMAND: server
      # OCIS_URL: ocis.owncloud.test
      PROXY_TLS: false
      # see https://github.com/owncloud/ocis/pull/675 /etc/ocis/proxy.json
      # PROXY_CONFIG_FILE: /proxy.json
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      REVA_GATEWAY: storage-gateway.owncloud.test:9142 # has an issue with webdav HERE
      # PROXY_LOG_LEVEL: debug
#      PROXY_CONFIG_FILE: "/var/tmp/ocis/.config/proxy-config.json"
      # PROXY_ENABLE_BASIC_AUTH: true

    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    # ports:
    #   - "9200:9200"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.entrypoints=https"
      # maps based on domain from https --> ocis.owncloud.test:9200
      - "traefik.http.routers.proxy.rule=Host(`${OCIS_DOMAIN:-ocis.owncloud.test}`)"
      - "traefik.http.routers.proxy.tls.certresolver=http"
      - "traefik.http.routers.proxy.service=proxy"
      - "traefik.http.services.proxy.loadbalancer.server.port=9200"
      # IMPORTANT - otherwise it will bind to "ocis-int" (although it should not be able to)
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_ocis-net"

  web:
    depends_on:
      - ocis
    extends:
        file: docker-compose.base.yml
        service: ocis
    networks:
      ocis-int:
        aliases:
          - web.owncloud.test
    environment:
      OCIS_RUN_EXTENSIONS: web
      OCIS_COMMAND: server

      WEB_HTTP_ADDR: web.owncloud.test:9100
      # override config.json
      WEB_UI_CONFIG: /etc/ocis/config.json
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    ports:
      - 9100:9100

 # proxy currently fails with "proxy error: EOF" when connecting to ocs->reva gateway, try separating proxy first?
  # ocs:
  #   depends_on:
  #     - ocis
  #   extends:
  #       file: docker-compose.base.yml
  #       service: ocis
  #   networks:
  #     ocis-int:
  #       aliases:
  #         - ocs.owncloud.test
  #   environment:
  #     OCIS_RUN_EXTENSIONS: ocs
  #     OCIS_COMMAND: server

  #     OCS_HTTP_ADDR: 0.0.0.0:9110
  #     # OCS_REVA_ADDRESS: storage-gateway.owncloud.test:9142
  #     REVA_GATEWAY: storage-gateway.owncloud.test:9142

  #   entrypoint:
  #     - /bin/sh
  #     - /entrypoint-override.sh
  #   ports:
  #     - 9110:9110

  graph:
    depends_on:
      - ocis
    extends:
        file: docker-compose.base.yml
        service: ocis
    networks:
      ocis-int:
        aliases:
          - graph.owncloud.test
    environment:
      OCIS_RUN_EXTENSIONS: graph
      OCIS_COMMAND: server

      GRAPH_HTTP_ADDR: graph.owncloud.test:9120
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    ports:
      - 9120:9120

  graph-explorer:
    depends_on:
      - ocis
    extends:
        file: docker-compose.base.yml
        service: ocis
    networks:
      ocis-int:
        aliases:
          - graph-explorer.owncloud.test
    environment:
      OCIS_RUN_EXTENSIONS: graph-explorer
      OCIS_COMMAND: server

      GRAPH_EXPLORER_HTTP_ADDR: graph-explorer.owncloud.test:9135
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    ports:
      - 9135:9135

volumes:
  certs:
  ocis-data:

networks:
  ocis-net:
    ipam:
      config:
        - subnet: 172.177.0.0/16
  ocis-int:
    ipam:
      config:
        - subnet: 10.103.0.1/16
